# Generated by Django 2.1.3 on 2018-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='hipeac.Project'),
        ),
    ]
