# Generated by Django 2.0.3 on 2018-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['type'], name='hipeac_pres_type_bff957_idx'),
        ),
        migrations.AlterModelTable(
            name='quote',
            table='hipeac_press_quote',
        ),
    ]
