# Generated by Django 2.1.2 on 2018-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_type', models.PositiveSmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze'), (9, 'Academic')], default=3)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete='CASCADE', related_name='sponsors', to='hipeac.Event')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='sponsored_events', to='hipeac.Institution')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='sponsored_events', to='hipeac.Project')),
            ],
            options={
                'ordering': ['sponsorship_type', '-amount', 'institution__name'],
            },
        ),
    ]
