# Generated by Django 2.1.1 on 2018-09-05 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hipeac.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hipeac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('blog', 'HiPEAC blog'), ('news', 'HiPEAC news'), ('release', 'HiPEAC press release'), ('jobs', 'Career news')], default='news', max_length=7)),
                ('publication_date', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('institutions', models.ManyToManyField(blank=True, related_name='articles', to='hipeac.Institution')),
                ('projects', models.ManyToManyField(blank=True, related_name='articles', to='hipeac.Project')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
            bases=(hipeac.models.mixins.UrlMixin, models.Model),
        ),
    ]
