# Generated by Django 3.2.8 on 2021-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipping",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("jobs", "Jobs"),
                    ("internships", "PhD Internships"),
                    ("industry", "Industry"),
                    ("innovation", "Innovation community"),
                    ("csw", "Computing Systems Week"),
                    ("conference", "HiPEAC Conference"),
                    ("acaces", "ACACES"),
                    ("vision", "HiPEAC Vision"),
                    ("roadshow", "HiPEAC Roadshow"),
                    ("collaborations", "Collaboration Grants"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="event",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("csw", "CSW"),
                    ("conference", "Conference"),
                    ("webinars", "Webinars"),
                    ("acaces", "ACACES Summer School"),
                    ("ec_meeting", "EC Consultation Meeting"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("jobs", "Jobs"),
                    ("internships", "PhD Internships"),
                    ("industry", "Industry"),
                    ("innovation", "Innovation community"),
                    ("csw", "Computing Systems Week"),
                    ("conference", "HiPEAC Conference"),
                    ("acaces", "ACACES"),
                    ("vision", "HiPEAC Vision"),
                    ("roadshow", "HiPEAC Roadshow"),
                    ("collaborations", "Collaboration Grants"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="video",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("jobs", "Jobs"),
                    ("internships", "PhD Internships"),
                    ("industry", "Industry"),
                    ("innovation", "Innovation community"),
                    ("csw", "Computing Systems Week"),
                    ("conference", "HiPEAC Conference"),
                    ("acaces", "ACACES"),
                    ("vision", "HiPEAC Vision"),
                    ("roadshow", "HiPEAC Roadshow"),
                    ("collaborations", "Collaboration Grants"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
