# Generated by Django 2.1.2 on 2018-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0002_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coffee', 'Coffee break'), ('lunch', 'Lunch break')], default='coffee', max_length=16)),
                ('date', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete='CASCADE', related_name='breaks', to='hipeac.Event')),
            ],
            options={
                'db_table': 'hipeac_event_break',
                'ordering': ['date', 'start_at'],
            },
        ),
    ]
