# Generated by Django 2.0.3 on 2018-03-27 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0002_auto_20180327_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hipeac_press_clipping',
                'ordering': ['-published_at'],
            },
        ),
    ]
