# Generated by Django 2.1.1 on 2018-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['page', 'key'], 'verbose_name': 'page block'},
        ),
        migrations.AlterModelOptions(
            name='roadshow',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('blog', 'HiPEAC Blog'), ('news', 'HiPEAC News'), ('release', 'HiPEAC Press Release'), ('jobs', 'HiPEAC Career News')], default='news', max_length=7),
        ),
    ]
