# Generated by Django 2.0.3 on 2018-03-27 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0003_clipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='clipping',
            options={'ordering': ['-publication_date']},
        ),
        migrations.RenameField(
            model_name='clipping',
            old_name='published_at',
            new_name='publication_date',
        ),
    ]
