# Generated by Django 3.2.8 on 2021-10-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0003_auto_20211026_1126"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="webinarregistration",
            name="hipeac_webi_uuid_aed0ab_idx",
        ),
        migrations.RemoveField(
            model_name="webinarregistration",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="webinarregistration",
            name="webinar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="hipeac.webinar"
            ),
        ),
    ]
