# Generated by Django 2.1.2 on 2018-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0003_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='processed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.TextField(default='[]', editable=False),
        ),
    ]
