# Generated by Django 2.1.1 on 2018-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0003_auto_20180906_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('jobs', 'Jobs'), ('internships', 'PhD Internships'), ('industry', 'Industry'), ('innovation', 'Innovation community'), ('csw', 'Computing Systems Week'), ('conference', 'HiPEAC Conference'), ('acaces', 'ACACES'), ('roadshow', 'HiPEAC Roadshow'), ('collaborations', 'Collaboration Grants')], max_length=16),
        ),
    ]
