# Generated by Django 4.0.6 on 2022-07-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0004_accompanyingperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="from_email",
            field=models.CharField(
                help_text="It can be a `Full Name &lt;email@domain.com&gt;` string or just an email address.",
                max_length=128,
                verbose_name="from",
            ),
        ),
    ]
