# Generated by Django 2.1.2 on 2018-10-11 10:58

from django.db import migrations, models
import django.db.models.deletion
import hipeac.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0004_auto_20181004_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(0, 'No'), (2, 'Yes'), (1, 'Yes, via the HiPEAC Jobs portal!')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('selected_candidate', models.TextField(blank=True, null=True)),
            ],
            bases=(hipeac.models.mixins.EditorMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_reminder',
        ),
        migrations.AddField(
            model_name='job',
            name='evaluation_sent_for',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reminder_sent_for',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobevaluation',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hipeac.Job'),
        ),
    ]
