# Generated by Django 3.2.8 on 2021-12-03 09:07

from django.db import migrations, models
import django_countries.fields
import hipeac.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0004_auto_20211029_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissemination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('general', 'General'), ('jobs', 'Jobs'), ('internships', 'PhD Internships'), ('industry', 'Industry'), ('innovation', 'Innovation community'), ('csw', 'Computing Systems Week'), ('conference', 'HiPEAC Conference'), ('acaces', 'ACACES'), ('vision', 'HiPEAC Vision'), ('roadshow', 'HiPEAC Roadshow'), ('collaborations', 'Collaboration Grants')], max_length=16, null=True)),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=250)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dissemination event',
                'ordering': ['-date'],
            },
            bases=(hipeac.models.mixins.UrlMixin, models.Model),
        ),
    ]
