# Generated by Django 2.1.1 on 2018-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0004_auto_20180907_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_url',
            field=models.URLField(editable=False, null=True),
        ),
    ]
