# Generated by Django 2.1 on 2018-08-20 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hipeac.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hipeac', '0004_auto_20180327_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=255)),
                ('header', models.TextField(blank=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Page block',
                'ordering': ['page', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/images', verbose_name='Image')),
                ('position', models.PositiveSmallIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['content_type', 'object_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
            ],
            bases=('flatpages.flatpage',),
        ),
        migrations.AlterField(
            model_name='institution',
            name='application_areas',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[hipeac.validators.validate_no_badwords]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='topics',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_areas',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='career_levels',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(validators=[hipeac.validators.validate_no_badwords]),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250, validators=[hipeac.validators.validate_no_badwords]),
        ),
        migrations.AlterField(
            model_name='job',
            name='topics',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='application_areas',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='application_areas',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[hipeac.validators.validate_no_badwords]),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='application_areas',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='topics',
            field=models.CharField(default='', max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hipeac.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('page', 'key')},
        ),
    ]
