# Generated by Django 2.1.2 on 2018-10-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0004_auto_20181004_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_reminder',
        ),
        migrations.AddField(
            model_name='job',
            name='reminded_deadline',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
