# Generated by Django 2.1.4 on 2018-12-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0005_auto_20181206_1436"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.RemoveField(
            model_name="track",
            name="event",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="url",
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sponsors", to="hipeac.Event"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_events",
                to="hipeac.Institution",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_events",
                to="hipeac.Project",
            ),
        ),
        migrations.DeleteModel(
            name="Track",
        ),
        migrations.AddField(
            model_name="room",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rooms", to="hipeac.Venue"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="hipeac.Room",
            ),
        ),
    ]
