# Generated by Django 2.1 on 2018-08-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0005_auto_20180820_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender', to='hipeac.Metadata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meal_preference',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'meal_preference'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_meal_preference', to='hipeac.Metadata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'job_position'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_job_position', to='hipeac.Metadata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'title'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_title', to='hipeac.Metadata'),
        ),
    ]
