# Generated by Django 3.2.8 on 2021-12-03 11:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0005_dissemination'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissemination',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dissemination',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
