# Generated by Django 4.1.3 on 2022-11-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0006_webinarproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferencePoster",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posters",
                        to="hipeac.conferenceregistration",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posters",
                        to="hipeac.session",
                    ),
                ),
            ],
            options={
                "db_table": "hipeac_conference_poster",
            },
        ),
    ]
