# Generated by Django 2.1.4 on 2018-12-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0006_auto_20181206_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="institution",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="hipeac.Institution"
            ),
        ),
    ]
