# Generated by Django 2.1 on 2018-08-27 12:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0007_mailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Presentation')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institutions', models.ManyToManyField(blank=True, help_text='Optionally, indicate institutions that will attend the event.', related_name='roadshow_events', to='hipeac.Institution')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
