# Generated by Django 4.1.3 on 2022-11-17 09:37

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0007_conferenceposter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadata",
            options={"ordering": ("type", "position", "value")},
        ),
        migrations.AddField(
            model_name="metadata",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=190), blank=True, default=list, editable=False, size=None
            ),
        ),
    ]
