# Generated by Django 2.1.4 on 2018-12-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hipeac', '0008_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='hipeac.Event')),
                ('members', models.ManyToManyField(related_name='committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hipeac_event_committee',
                'ordering': ('position',),
            },
        ),
    ]
