# Generated by Django 2.1.1 on 2018-09-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hipeac', '0008_auto_20180827_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='hipeac_pres_type_bff957_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Owner'), (7, 'Administrator'), (1, 'Guest')], db_index=True),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['type'], name='hipeac_comm_type_02821d_idx'),
        ),
        migrations.AlterModelTable(
            name='clipping',
            table='hipeac_communication_clipping',
        ),
        migrations.AlterModelTable(
            name='quote',
            table='hipeac_communication_quote',
        ),
    ]
