# Generated by Django 2.1.4 on 2018-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0009_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='hipeac.Institution'),
        ),
    ]
