# Generated by Django 4.1.3 on 2022-11-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0009_alter_job_keywords_alter_membership_keywords_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadata",
            options={"ordering": ("type", "position", "value"), "verbose_name_plural": "Metadata"},
        ),
    ]
