# Generated by Django 2.1.5 on 2019-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0011_session_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration", name="manual_extra_fees", field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
