# Generated by Django 4.1.3 on 2022-11-23 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0011_remove_hipeac_is_visible_project_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationarea",
            options={"ordering": ("application_area__position", "application_area__value")},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("topic__position", "topic__value")},
        ),
    ]
