# Generated by Django 4.1.3 on 2022-11-29 13:33

import django.db.models.deletion
import django_countries.fields
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0012_alter_applicationarea_options_alter_topic_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFair",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, unique=True)),
                (
                    "is_virtual",
                    models.BooleanField(default=False, help_text="Is it a virtual fair?", verbose_name="virtual"),
                ),
                ("name", models.CharField(max_length=250)),
                ("presentation", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "city",
                    models.CharField(blank=True, help_text="Empty for virtual events.", max_length=100, null=True),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, db_index=True, help_text="Empty for virtual events.", max_length=2, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_fair",
                        to="hipeac.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job fair",
                "db_table": "hipeac_job_fair",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="JobFairRegistration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="hipeac.jobfair"
                    ),
                ),
                ("jobs", models.ManyToManyField(blank=True, related_name="jobs", to="hipeac.job")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_fair_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hipeac_job_fair_registration",
                "ordering": ("-id",),
                "unique_together": {("fair", "user")},
            },
        ),
    ]
