# Generated by Django 4.1.3 on 2022-11-30 08:01

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0013_jobfair_jobfairregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=190), blank=True, default=list, size=None
            ),
        ),
    ]
