# Generated by Django 2.1.5 on 2019-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0014_auto_20190121_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programme',
            field=models.CharField(blank=True, choices=[('FP7', 'FP7'), ('H2020', 'H2020'), ('ECSEL', 'ECSEL'), ('OTHER', 'Other')], max_length=5, null=True),
        ),
    ]
