# Generated by Django 4.1.6 on 2023-02-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0015_techtransferaward_has_price_money_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFairCompany",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="companies", to="hipeac.jobfair"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="job_fairs", to="hipeac.institution"
                    ),
                ),
                ("users", models.ManyToManyField(blank=True, related_name="job_fairs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Job fair companies",
                "db_table": "hipeac_job_fair_company",
                "unique_together": {("fair", "institution")},
            },
        ),
    ]
