# Generated by Django 2.1.5 on 2019-01-22 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0016_auto_20190121_2024"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("affiliation", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("motivation", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "membership_type",
                    models.CharField(
                        blank=True,
                        choices=[("member", "Member"), ("member,non-eu", "Associated member")],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "Accepted"), ("NO", "Rejected"), ("UN", "Pending")], default="UN", max_length=2
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "hipeac_steering_membership_request", "ordering": ("-created_at",)},
        ),
    ]
