# Generated by Django 4.1.6 on 2023-03-01 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0017_file_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hipeacpartner",
            options={"ordering": ("hipeac", "position", "institution__name")},
        ),
    ]
