# Generated by Django 2.1.5 on 2019-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0017_membershiprequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiprequest",
            name="status",
        ),
        migrations.AddField(
            model_name="membershiprequest",
            name="accepted",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
