# Generated by Django 4.1.6 on 2023-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0018_alter_hipeacpartner_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "hipeac_email_recipient",
            },
        ),
    ]
