# Generated by Django 2.1.7 on 2019-02-14 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hipeac', '0022_privatefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevaluation',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='hipeac.Job'),
        ),
        migrations.AddField(
            model_name='jobevaluation',
            name='selected_user',
            field=models.ForeignKey(blank=True, help_text='Internal use only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobevaluation',
            name='selected_candidate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
