# Generated by Django 4.2.6 on 2023-11-06 13:52

from django.db import migrations, models


def roadshow_to_dissemination(apps, schema_editor):
    """Migrate to Dissemination, including images, links and institutions."""

    Dissemination = apps.get_model("hipeac", "Dissemination")
    Roadshow = apps.get_model("hipeac", "Roadshow")
    Image = apps.get_model("hipeac", "Image")
    Link = apps.get_model("hipeac", "Link")
    RelatedInstitution = apps.get_model("hipeac", "RelatedInstitution")

    ct = apps.get_model("contenttypes", "ContentType").objects.get_for_model(Dissemination)

    for roadshow in Roadshow.objects.all():
        did = Dissemination.objects.create(
            type="roadshow",
            start_date=roadshow.start_date,
            end_date=roadshow.end_date,
            event=roadshow.name,
            country=roadshow.country,
            description=roadshow.description,
        )

        for image in Image.objects.filter(content_type__model="roadshow", object_id=roadshow.id):
            image.content_type = ct
            image.object_id = did.id
            image.save()

        for link in Link.objects.filter(content_type__model="roadshow", object_id=roadshow.id):
            link.content_type = ct
            link.object_id = did.id
            link.save()

        for rel in RelatedInstitution.objects.filter(content_type__model="roadshow", object_id=roadshow.id):
            rel.content_type = ct
            rel.object_id = did.id
            rel.save()


def url_to_links(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Dissemination = apps.get_model("hipeac", "Dissemination")
    Link = apps.get_model("hipeac", "Link")

    for dis in Dissemination.objects.all():
        ct = ContentType.objects.get_for_model(Dissemination)

        if dis.external_url:
            Link.objects.create(
                content_type=ct,
                object_id=dis.id,
                type="website",
                url=dis.external_url,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("hipeac", "0022_paper_conference_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dissemination",
            options={"ordering": ("-start_date",), "verbose_name": "Dissemination event"},
        ),
        migrations.RenameField(
            model_name="dissemination",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="dissemination",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        # -----
        migrations.RunPython(roadshow_to_dissemination),
        migrations.RunPython(url_to_links),
        # -----
        migrations.RemoveField(
            model_name="dissemination",
            name="external_url",
        ),
        migrations.DeleteModel(
            name="Roadshow",
        ),
    ]
