# Generated by Django 2.1.5 on 2019-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0023_auto_20190214_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="presentation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
