# Generated by Django 4.2.8 on 2023-12-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0023_delete_roadshow_remove_dissemination_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cc', to='hipeac.project')),
            ],
            options={
                'db_table': 'cc_projects',
                'ordering': ('project__name',),
            },
        ),
    ]
