# Generated by Django 4.2.9 on 2024-03-27 07:26

import django.core.validators
from django.db import migrations, models
import hipeac.functions


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0024_cc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cc',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='cc',
            name='project',
        ),
        migrations.AddField(
            model_name='cc',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=hipeac.functions.get_images_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='cc',
            name='name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
    ]
