# Generated by Django 4.2.11 on 2024-06-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0025_alter_cc_options_remove_cc_project_cc_image_cc_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CC',
        ),
    ]
