# Generated by Django 2.1.7 on 2019-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0025_auto_20190312_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication", name="selected", field=models.BooleanField(default=False),
        ),
    ]
