# Generated by Django 2.1.7 on 2019-05-03 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0029_auto_20190401_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=250)),
                ('organizers', models.TextField()),
                ('summary', models.TextField()),
                ('projects', models.TextField(blank=True, null=True)),
                ('workshop_deadlines', models.TextField(blank=True, null=True)),
                ('tutorial_biblio', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=250)),
                ('session_format', models.CharField(max_length=250)),
                ('expected_attendees', models.CharField(max_length=250)),
                ('room_configuration', models.CharField(max_length=250)),
                ('previous_editions', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('application_areas', models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('topics', models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_proposals', to='hipeac.Event')),
            ],
        ),
    ]
