# Generated by Django 2.1.7 on 2019-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0030_sessionproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_ready",
            field=models.BooleanField(default=False, help_text="Is programme ready?"),
        ),
    ]
