# Generated by Django 2.2.2 on 2019-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0034_auto_20190606_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine", name="downloads", field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
