# Generated by Django 2.2.3 on 2019-07-03 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0037_magazine_event"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="user",),
        migrations.AddField(
            model_name="video",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="videos", to=settings.AUTH_USER_MODEL),
        ),
    ]
