# Generated by Django 2.2.3 on 2019-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0038_auto_20190703_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='add_to_euraxess',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
