# Generated by Django 2.2.5 on 2019-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0043_auto_20190917_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
