# Generated by Django 2.2.7 on 2019-11-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0045_auto_20191014_1154"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hipeac",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="hipeac.Project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HipeacPartner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("tasks", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "hipeac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="partners", to="hipeac.Hipeac"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="hipeac.Institution"),
                ),
                (
                    "representatives",
                    models.ManyToManyField(related_name="hipeac_projects", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
