# Generated by Django 2.2.7 on 2019-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0046_hipeac_hipeacpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipeac',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
