# Generated by Django 2.2.7 on 2019-11-27 09:39

from django.db import migrations, models
import hipeac.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0048_auto_20191125_1151"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("location", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("url_webex", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-start_at"]},
            bases=(hipeac.models.mixins.LinkMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="hipeacpartner",
            options={"ordering": ["hipeac", "position"]},
        ),
    ]
