# Generated by Django 2.2.7 on 2019-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0050_actionpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='status',
            field=models.CharField(choices=[('discarded', 'Discarded'), ('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('finalized', 'Finalized')], default='UN', max_length=16),
        ),
    ]
