# Generated by Django 2.2.8 on 2019-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0051_auto_20191128_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="private/steering/meeting"),
        ),
    ]
