# Generated by Django 2.2.9 on 2020-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0056_openevent_openregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='openregistration',
            name='country_raw',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
