# Generated by Django 2.2.9 on 2020-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0058_auto_20200213_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="openregistration",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
