# Generated by Django 3.0.5 on 2020-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0068_auto_20200428_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("dblp", "DBLP"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("twitter", "Twitter"),
                    ("youtube", "YouTube"),
                    ("easychair", "EasyChair"),
                    ("cordis", "Cordis"),
                    ("google_maps", "Google Maps"),
                    ("google_photos", "Google Photos"),
                    ("zoom", "Zoom.us"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
