# Generated by Django 3.0.5 on 2020-04-30 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0070_course_coursesession"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="teacher",),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(blank=True, related_name="courses", to=settings.AUTH_USER_MODEL),
        ),
    ]
