# Generated by Django 3.0.5 on 2020-04-30 08:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0071_auto_20200430_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.CharField(
                blank=True,
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
    ]
