# Generated by Django 3.0.5 on 2020-05-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0073_auto_20200501_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='courses',
            field=models.ManyToManyField(related_name='registrations', to='hipeac.Course'),
        ),
        migrations.AddField(
            model_name='registrationlog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hipeac.Course'),
        ),
        migrations.AlterField(
            model_name='registrationlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hipeac.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationlog',
            unique_together={('registration', 'course'), ('registration', 'session')},
        ),
    ]
