# Generated by Django 3.0.6 on 2020-05-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0074_auto_20200502_1301"),
    ]

    operations = [
        migrations.RenameField(model_name="event", old_name="travel_info", new_name="logistics",),
    ]
