# Generated by Django 3.0.6 on 2020-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0075_auto_20200504_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job", name="email", field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
