# Generated by Django 3.0.7 on 2020-06-19 08:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0078_auto_20200527_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poster",
            name="topics",
            field=models.CharField(
                blank=True,
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="AcacesPosterAbstract",
        ),
    ]
