# Generated by Django 3.0.7 on 2020-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0079_auto_20200619_1034"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": [
                    "legacy_date",
                    "session_type__position",
                    "legacy_start_at",
                    "room__position",
                    "legacy_end_at",
                ]
            },
        ),
        migrations.RenameField(model_name="session", old_name="date", new_name="legacy_date",),
        migrations.RenameField(model_name="session", old_name="end_at", new_name="legacy_end_at",),
        migrations.RenameField(model_name="session", old_name="start_at", new_name="legacy_start_at",),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["event", "legacy_date"], name="hipeac_sess_event_i_d4b8b1_idx"),
        ),
    ]
