# Generated by Django 3.0.7 on 2020-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0081_auto_20200623_0827"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["session_type__position", "start_at", "room__position", "end_at"]},
        ),
        migrations.RemoveField(
            model_name="session",
            name="legacy_date",
        ),
        migrations.RemoveField(
            model_name="session",
            name="legacy_end_at",
        ),
        migrations.RemoveField(
            model_name="session",
            name="legacy_start_at",
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["event"], name="hipeac_sess_event_i_7b3339_idx"),
        ),
    ]
