# Generated by Django 3.0.8 on 2020-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0082_auto_20200623_0941'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='hipeac_sess_event_i_aa2af2_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='hipeac_sess_event_i_d4b8b1_idx',
        ),
        migrations.AddField(
            model_name='poster',
            name='breakout_room',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
