# Generated by Django 3.0.8 on 2020-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0083_auto_20200714_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='abstract',
            field=models.FileField(blank=True, null=True, upload_to='private/poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='breakout_room',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='private/poster'),
        ),
    ]
