# Generated by Django 3.0.8 on 2020-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipeac', '0084_auto_20200714_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='private/poster'),
        ),
    ]
