# Generated by Django 3.1 on 2020-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0085_poster_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="zoom_attendee_report",
            field=models.FileField(blank=True, null=True, upload_to="private/zoom"),
        ),
    ]
