# Generated by Django 3.1.2 on 2020-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0086_coursesession_zoom_attendee_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="session", name="zoom_webinar_id", field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
