# Generated by Django 3.1.2 on 2020-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0087_session_zoom_webinar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session", name="zoom_webinar_id", field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
