# Generated by Django 3.1.2 on 2020-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0089_sessionaccesslink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionaccesslink",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
