# Generated by Django 3.1.5 on 2021-01-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hipeac", "0092_registration_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="speakers",
            field=models.ManyToManyField(blank=True, related_name="talks", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="session",
            name="main_speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_talks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
