# Generated by Django 3.1.5 on 2021-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0093_auto_20210115_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="keywords",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
