# Generated by Django 3.1.6 on 2021-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0094_auto_20210115_1209"),
    ]

    operations = [
        migrations.AlterField(model_name="block", name="key", field=models.CharField(max_length=48),),
    ]
