# Generated by Django 3.1.6 on 2021-02-19 09:06

from django.db import migrations, models
import django.db.models.deletion
import hipeac.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0095_auto_20210205_1250"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionArticle",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250)),
                ("authors", models.TextField(null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="private/vision/article")),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "vision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="hipeac.vision"
                    ),
                ),
            ],
            options={
                "db_table": "hipeac_vision_article",
                "ordering": ("position",),
            },
            bases=(hipeac.models.mixins.LinkMixin, models.Model),
        ),
    ]
