# Generated by Django 3.1.6 on 2021-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0096_visionarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="visionarticle",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visionarticle",
            name="dimension",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="visionarticle",
            name="authors",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
