# Generated by Django 3.1.6 on 2021-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0097_auto_20210219_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="visionarticle", name="downloads", field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(model_name="vision", name="downloads", field=models.PositiveIntegerField(default=0),),
    ]
