# Generated by Django 3.2.2 on 2021-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0100_auto_20210602_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Pending"), (1, "Accepted internally"), (2, "Accepted"), (9, "Rejected")],
                default=2,
                help_text="Status is only used for physical Summer Schools were grants need to be distributed.",
            ),
        ),
    ]
