# Generated by Django 3.2.2 on 2021-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0101_registration_status"),
    ]

    operations = [
        migrations.AddField(model_name="event", name="custom_data", field=models.JSONField(default=dict),),
    ]
