# Generated by Django 3.2.2 on 2021-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hipeac", "0102_event_custom_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="visionarticle", name="file",),
        migrations.AddField(
            model_name="visionarticle",
            name="doi_url",
            field=models.URLField(default="https://doi.org"),
            preserve_default=False,
        ),
    ]
